"""Read/write helper for the systemd `EnvironmentFile` this app is deployed
with (`/srv/curodav/shared/.env`, generated by `scripts/curodav-ctl`'s
`write_env_template` -- see that script for the file's exact format and
permissions). Stdlib-only, no new runtime dependency, same convention as
`src/image_sniff.py`/`src/auth.py`.

Why this exists: `CC_RADICALE_URL`/`CC_RADICALE_USER`/`CC_RADICALE_PASSWORD`
and `CC_AUTH_USERNAME`/`CC_AUTH_PASSWORD` are plain OS environment variables
(config.py's own docstring -- there is no `.env`-parsing inside the app
itself, systemd's `EnvironmentFile=` injects them before the process even
starts). Before this module existed, changing any of them meant SSHing in
and hand-editing the file -- every Settings route that touched a
env-configured value just said so and no-opped (routers/settings.py's
"edit curodav.env and restart" messages). Settings > General's Account card
(routers/settings.py::account_settings) now writes here directly instead,
with a "Restart app" button (::restart_app) to actually pick the change up
-- see that route's own docstring for the full flow.

Format assumptions, matching `write_env_template`'s own output and
systemd.exec(5)'s "Environment Variables in Spawned Processes" simplified
syntax (NOT full shell): one `KEY=VALUE` per line, optional leading `#`
for a commented-out template line, blank lines and full-line comments
preserved verbatim, no line continuations. A value written by this module
is always double-quoted with `\\` and `"` escaped -- conservative, valid
under systemd's own quoting rules, and safe for a password that might
contain `#`, whitespace, or `=`."""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path

# KEY=VALUE (optionally commented-out with a leading '#'). Group 1: '#' or
# '' (whether this line is a live var or a commented-out template line).
# Group 2: the key. Everything after the first '=' is the raw value,
# handled separately (quotes/escaping vary line to line).
_LINE_RE = re.compile(r"^(#\s*)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def _unquote(raw: str) -> str:
    """Best-effort value-side parse: strips a single layer of matching
    quotes and un-escapes `\\"`/`\\\\` inside double quotes. An unquoted
    value (the common case for `write_env_template`'s own uncommented
    examples, e.g. `CC_DB_PATH=...`) is returned as-is, just stripped of
    surrounding whitespace."""
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ("'", '"'):
        inner = raw[1:-1]
        if raw[0] == '"':
            inner = inner.replace('\\"', '"').replace("\\\\", "\\")
        return inner
    return raw


def _quote(value: str) -> str:
    """Always double-quotes, escaping `\\` and `"` -- see module
    docstring. Deliberately not "quote only if needed": a value with no
    special characters quotes just as validly, and always-quote means one
    code path instead of two (some values quoted, some not) to reason
    about."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def read_env_file(path: str | Path) -> dict[str, str]:
    """Every live (uncommented) `KEY=VALUE` pair in `path`, values
    unquoted/unescaped. Commented-out template lines (`#CC_RADICALE_URL=
    ...`) are not included -- they're not actually set. Returns `{}` for
    a missing file rather than raising, since a fresh/non-standard install
    may not have `CC_ENV_FILE` pointing at a real file yet."""
    p = Path(path)
    if not p.is_file():
        return {}
    result: dict[str, str] = {}
    for line in p.read_text(encoding="utf-8").splitlines():
        m = _LINE_RE.match(line)
        if not m or m.group(1):  # no match, or commented-out
            continue
        result[m.group(2)] = _unquote(m.group(3))
    return result


def update_env_file(path: str | Path, updates: dict[str, str]) -> None:
    """Persists `updates` (key -> new value) into the env file at `path`,
    preserving every other line verbatim (comments, blank lines, unrelated
    vars, ordering). For each key:
      - a live `KEY=...` line has its value replaced in place;
      - else a commented-out `#KEY=...` template line is uncommented and
        its value replaced (this is exactly the shape `write_env_template`
        ships for `CC_RADICALE_*`/`CC_AUTH_USERNAME`/`CC_AUTH_PASSWORD` --
        turning a Settings save into "uncomment and fill in" rather than a
        blind append keeps the file's own template comments/ordering
        intact instead of duplicating the key further down);
      - else (key appears nowhere yet) a new `KEY=VALUE` line is appended.

    Written atomically: a temp file in the same directory (so the final
    `os.replace` is a same-filesystem rename, not a cross-device copy),
    with the original file's permission bits copied over before the swap
    -- `scripts/curodav-ctl`'s `write_env_template` sets `root:curodav`
    0660 specifically so the app process (running as `curodav`) can write
    here; a naive open-and-write would silently lose that mode on some
    filesystems/umasks, and a plain rename onto a nonexistent temp+chmod
    default would too. Raises whatever the underlying I/O error is (a
    caller with no write access, e.g. a misconfigured deploy, should not
    have that failure swallowed) -- the route calling this catches it and
    turns it into a Settings error note instead of a 500.
    """
    p = Path(path)
    remaining = dict(updates)
    lines: list[str] = p.read_text(encoding="utf-8").splitlines() if p.is_file() else []

    for i, line in enumerate(lines):
        m = _LINE_RE.match(line)
        if not m:
            continue
        key = m.group(2)
        if key in remaining:
            lines[i] = f"{key}={_quote(remaining.pop(key))}"

    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        for key, value in remaining.items():
            lines.append(f"{key}={_quote(value)}")

    new_text = "\n".join(lines) + "\n"

    fd, tmp_name = tempfile.mkstemp(dir=str(p.parent), prefix=f".{p.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(new_text)
        if p.is_file():
            os.chmod(tmp_name, p.stat().st_mode)
        os.replace(tmp_name, p)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise
