#!/usr/bin/env bash
# Install Command Center Web (curodav) with Docker Compose.
#
#   sudo bash install.sh                   # the app
#   sudo bash install.sh --with-radicale   # app + optional CalDAV/CardDAV server
#
# What it sets up:
#   /opt/curodav          the repo (git clone) -- also the build context
#   /etc/curodav          config: curodav.env (0640 root:root)
#   curodav + curodav-radicale containers (named volumes for all data)
#
# Safe to re-run: pulls the latest repo, rebuilds the image, and never
# overwrites an existing /etc/curodav/curodav.env.
set -euo pipefail

REPO_URL="https://github.com/istorie-petru/curodav.git"
REPO_DIR="${CC_REPO_DIR:-/opt/curodav}"
CONF_DIR="/etc/curodav"
COMPOSE=(docker compose -f "$REPO_DIR/deploy/docker/docker-compose.yml")
WITH_RADICALE=0

for arg in "$@"; do
  case "$arg" in
    --with-radicale) WITH_RADICALE=1 ;;
    --repo-dir=*)    REPO_DIR="${arg#*=}" ;;
    *) echo "install.sh: unknown option: $arg" >&2; exit 2 ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "install.sh: this installer must run as root (sudo)." >&2
  exit 1
fi

# --- prerequisites --------------------------------------------------------
for tool in git docker; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "install.sh: missing prerequisite: $tool" >&2
    exit 1
  fi
done
docker compose version >/dev/null 2>&1 || {
  echo "install.sh: the Docker Compose plugin is required (docker compose)." >&2
  exit 1
}

# --- repo -----------------------------------------------------------------
if [ -d "$REPO_DIR/.git" ]; then
  echo "==> Updating existing repo at $REPO_DIR..."
  git -C "$REPO_DIR" pull --ff-only
else
  echo "==> Cloning $REPO_URL -> $REPO_DIR ..."
  mkdir -p "$(dirname "$REPO_DIR")"
  git clone --depth 1 "$REPO_URL" "$REPO_DIR"
fi

# --- config dir -----------------------------------------------------------
install -d -m 0750 "$CONF_DIR"
ENV_FILE="$CONF_DIR/curodav.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "==> Writing $ENV_FILE (from the example)..."
  install -m 0644 "$REPO_DIR/deploy/docker/curodav.env.example" "$ENV_FILE"
fi

# --- optional Radicale companion ---------------------------------------------
if [ "$WITH_RADICALE" = 1 ]; then
  RADICALE_USER="${CC_RADICALE_USER:-curodav}"
  USERS_FILE="$REPO_DIR/deploy/docker/radicale/users"
  if [ ! -f "$USERS_FILE" ]; then
    RADICALE_PASSWORD="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 18)"
    printf '%s:%s\n' "$RADICALE_USER" "$RADICALE_PASSWORD" > "$USERS_FILE"
    chmod 0600 "$USERS_FILE"
    if ! grep -q '^CC_RADICALE_URL=' "$ENV_FILE"; then
      printf '\n# Radicale sync credentials (generated by install.sh --with-radicale)\nCC_RADICALE_URL=http://radicale:5232/%s/\nCC_RADICALE_USER=%s\nCC_RADICALE_PASSWORD=%s\n' \
        "$RADICALE_USER" "$RADICALE_USER" "$RADICALE_PASSWORD" >> "$ENV_FILE"
    fi
    echo ""
    echo "Generated Radicale credentials (also stored in $ENV_FILE):"
    echo "    URL:      http://radicale:5232/$RADICALE_USER/  (inside the app container)"
    echo "    user:     $RADICALE_USER"
    echo "    password: $RADICALE_PASSWORD"
    echo ""
  fi
fi

# --- build + run ------------------------------------------------------------
echo "==> Building the image and starting the service(s)..."
COMPOSE_ARGS=(up -d --build)
if [ "$WITH_RADICALE" = 1 ]; then
  COMPOSE_ARGS=(--profile sync "${COMPOSE_ARGS[@]}")
fi
"${COMPOSE[@]}" "${COMPOSE_ARGS[@]}"

echo ""
echo "==> Done. Container status:"
"${COMPOSE[@]}" ps

echo ""
echo "    The app listens on http://127.0.0.1:8000 (from this host)."
echo "    Update later with: sudo bash $REPO_DIR/deploy/docker/update.sh"