"""src/env_file.py -- the read/write helper for this app's own systemd
EnvironmentFile (see that module's docstring for the full "why"). Covers
read_env_file (live vars only, commented-out template lines excluded) and
update_env_file (replace a live line, uncomment+replace a template line,
append a brand-new key, quoting/escaping round-trips, atomicity/permission
preservation, and a missing-file/missing-directory failure surfacing as a
real exception rather than silently doing nothing)."""

from __future__ import annotations

import os
import stat

import pytest

from src import env_file


SAMPLE = """# curodav configuration -- generated by curodav-ctl install
CC_DB_PATH=/srv/curodav/shared/data/cache.sqlite
CC_SYNC_INTERVAL=60
CC_AUTH_SECRET=abc123

# Uncomment to pre-provision the single-user login instead of using /setup:
# CC_AUTH_USERNAME=you
# CC_AUTH_PASSWORD=change-me

# Optional CalDAV/CardDAV sync against a Radicale server.
# CC_RADICALE_URL=http://127.0.0.1:5232/curodav/
# CC_RADICALE_USER=curodav
# CC_RADICALE_PASSWORD=
"""


@pytest.fixture()
def env_path(tmp_path):
    p = tmp_path / ".env"
    p.write_text(SAMPLE)
    os.chmod(p, 0o660)
    return p


class TestReadEnvFile:
    def test_reads_live_vars_only(self, env_path):
        result = env_file.read_env_file(env_path)
        assert result == {
            "CC_DB_PATH": "/srv/curodav/shared/data/cache.sqlite",
            "CC_SYNC_INTERVAL": "60",
            "CC_AUTH_SECRET": "abc123",
        }
        # Commented-out template lines are not "set".
        assert "CC_AUTH_USERNAME" not in result
        assert "CC_RADICALE_URL" not in result

    def test_missing_file_returns_empty_dict(self, tmp_path):
        assert env_file.read_env_file(tmp_path / "nope.env") == {}


class TestUpdateEnvFile:
    def test_replaces_a_live_line_in_place(self, env_path):
        env_file.update_env_file(env_path, {"CC_SYNC_INTERVAL": "120"})
        assert env_file.read_env_file(env_path)["CC_SYNC_INTERVAL"] == "120"
        # Everything else untouched.
        assert env_file.read_env_file(env_path)["CC_DB_PATH"] == "/srv/curodav/shared/data/cache.sqlite"

    def test_uncomments_and_fills_a_template_line(self, env_path):
        env_file.update_env_file(env_path, {"CC_AUTH_USERNAME": "petru", "CC_AUTH_PASSWORD": "hunter2"})
        text = env_path.read_text()
        assert "# CC_AUTH_USERNAME=you" not in text
        result = env_file.read_env_file(env_path)
        assert result["CC_AUTH_USERNAME"] == "petru"
        assert result["CC_AUTH_PASSWORD"] == "hunter2"
        # The template's own comment line above it survives untouched.
        assert "# Uncomment to pre-provision" in text

    def test_appends_a_brand_new_key(self, env_path):
        env_file.update_env_file(env_path, {"CC_NEW_THING": "1"})
        assert env_file.read_env_file(env_path)["CC_NEW_THING"] == "1"

    def test_round_trips_special_characters(self, env_path):
        tricky = 'p@ss "word" with \\backslash and # hash and spaces'
        env_file.update_env_file(env_path, {"CC_AUTH_PASSWORD": tricky})
        assert env_file.read_env_file(env_path)["CC_AUTH_PASSWORD"] == tricky

    def test_preserves_file_mode(self, env_path):
        os.chmod(env_path, 0o660)
        env_file.update_env_file(env_path, {"CC_SYNC_INTERVAL": "90"})
        mode = stat.S_IMODE(os.stat(env_path).st_mode)
        assert mode == 0o660

    def test_multiple_keys_in_one_call(self, env_path):
        env_file.update_env_file(
            env_path,
            {
                "CC_RADICALE_URL": "http://127.0.0.1:5232/petru/",
                "CC_RADICALE_USER": "petru",
                "CC_RADICALE_PASSWORD": "hunter2",
            },
        )
        result = env_file.read_env_file(env_path)
        assert result["CC_RADICALE_URL"] == "http://127.0.0.1:5232/petru/"
        assert result["CC_RADICALE_USER"] == "petru"
        assert result["CC_RADICALE_PASSWORD"] == "hunter2"

    def test_missing_parent_directory_raises(self, tmp_path):
        with pytest.raises(OSError):
            env_file.update_env_file(tmp_path / "nosuchdir" / ".env", {"X": "1"})

    def test_creating_new_file_from_scratch(self, tmp_path):
        p = tmp_path / "fresh.env"
        env_file.update_env_file(p, {"CC_AUTH_USERNAME": "petru"})
        assert env_file.read_env_file(p) == {"CC_AUTH_USERNAME": "petru"}
